### ISSUE TITLE
unable to protonate. 

### ISSUE THREAD

**Issue by ygk2zhang** [mholmboe/atom#2]
Hi,

I am using Matlab 2020a. When I follow this example I get this error when I try to protonate all the oxygens.

atom=import_atom('Pyrophyllite.pdb');
Found .pdb file
filename =
    'Pyrophyllite.pdb'
.pdb file imported
Looking up bonds
Calculating the distance matrix
i =
    40
Looking for neighbours/bonds
Composition info:
composition = 
  struct with fields:

     resnames: {'PYR'}
    nresidues: 1
       natoms: 40
Atom_types =
  1×5 cell array
    {'Al'}    {'H'}    {'O'}    {'Oh'}    {'Si'}
Atom_numbers =
     4     4    20     4     8
The box dimensions are:
Box_dim =
    5.1600    8.9658    9.1897         0         0         0         0   -1.6966         0
>> atom(strcmp([atom.type],'H'))=[];
>> Hatom = protonate_atom(atom,Box_dim)
Assuming all oxygen atoms should have 2 neighbours...
else also supply an ind vector for sites to protonate!
Dot indexing is not supported for variables of this type.
Error in dist_matrix_atom (line 32)

**Comment by ygk2zhang** [comment]
Hello. I have done more testing and it seems that the command
**Hatom = protonate_atom(atom,Box_dim)**
Does not work for small unit cells.  Once again, thank you for the code.

**Comment by mholmboe** [comment]
Hi, Sorry for the late reply. I think I fixed it so download the latest version!
